/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/amarcozzi/homebrew/Cellar/nim/0.17.0/nim/lib -o /Users/amarcozzi/Desktop/NIM_playground/nimcache/amof.o /Users/amarcozzi/Desktop/NIM_playground/nimcache/amof.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Table_MCOwvEd9cS88yVcSkkw9bO9aQ Table_MCOwvEd9cS88yVcSkkw9bO9aQ;
typedef struct TY_SFipDZIkFtPcrLs0AGBBjQ TY_SFipDZIkFtPcrLs0AGBBjQ;
typedef struct TY_8ZxhPt1NwfElsJs8zUSV9bg TY_8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct OptParser_w3uFmxpwEmgEXFUJjUl10w OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct TNimObject TNimObject;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Slice_qL3WGViqT0p5sVr4YFHsLg Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct CountTable_WWp0VSBtrctjwzspLeGpeg CountTable_WWp0VSBtrctjwzspLeGpeg;
typedef struct TY_jwzrUFjG9akTIJTBBFvvqxw TY_jwzrUFjG9akTIJTBBFvvqxw;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct TY_XOVT24GHXwqiEj5GCsEGCA TY_XOVT24GHXwqiEj5GCsEGCA;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct  Table_MCOwvEd9cS88yVcSkkw9bO9aQ  {
TY_SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct TY_8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NU8 CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct  TNimObject  {
TNimType* m_type;
};
struct  OptParser_w3uFmxpwEmgEXFUJjUl10w  {
  TNimObject Sup;
TY_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct  Slice_qL3WGViqT0p5sVr4YFHsLg  {
NI a;
NI b;
};
struct  CountTable_WWp0VSBtrctjwzspLeGpeg  {
TY_jwzrUFjG9akTIJTBBFvvqxw* data;
NI counter;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct TY_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  TY_8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_jwzrUFjG9akTIJTBBFvvqxw {
  TGenericSeq Sup;
  TY_XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, initTable_Pb6nsyDUqkcuOfIqNGZ04Q)(NI initialSize, Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_4)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, add_CM5QBhJw8HvPuuaSW9c6LyQ)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, enlarge_9bBNTfkcWUAIzJYEZbqre3w)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t);
N_NIMCALL(void, rawInsert_i52hhunrCCXlXL7airLPUA)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, TY_SFipDZIkFtPcrLs0AGBBjQ** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_9b2gsSftUX2T20Nv0GQyaugtables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_6)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_7)(void);
N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NIMCALL(void, npo2next)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_NIMCALL(NIM_BOOL, hasKey_73Yi0wXG00JVMtJDwIey2w)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key);
static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaug_2tables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, dollar__cPfIGYedWWtjGdyyA7sVuw)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t);
N_NIMCALL(NI, len_i2Zrth1XTX9c3vCk9aWi3N9bQ)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t);
N_NIMCALL(NimStringDesc**, X5BX5D__IdJl6zz7UBsTsE2mzgQNJA)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_13)(void);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_14)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_15)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_16)(void);
N_NIMCALL(NIM_BOOL, substrEq_7ngl0F5lryTkSAj7sYQ7pw)(NimStringDesc* s, NI pos, NimStringDesc* substr);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x);
static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, initCountTable_n9cD2kEnW9cUab3V9bqtBxaTw)(NI initialSize, CountTable_WWp0VSBtrctjwzspLeGpeg* Result);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_29)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_30)(void);
N_NIMCALL(void, inc_hCwWEfjYY2mbkXPFg2lZFQ)(CountTable_WWp0VSBtrctjwzspLeGpeg* t, NimStringDesc* key, NI val);
N_NIMCALL(NI, rawGet_ExyNSxYFFaAiKxJjTjvq2w)(CountTable_WWp0VSBtrctjwzspLeGpeg t, NimStringDesc* key);
N_NIMCALL(void, enlarge_jFpBafF2fWVni1oyF0vlQQ)(CountTable_WWp0VSBtrctjwzspLeGpeg* t);
N_NIMCALL(void, rawInsert_4Pv0wuM2j9aB1ybb1n9bQSkQ)(CountTable_WWp0VSBtrctjwzspLeGpeg t, TY_jwzrUFjG9akTIJTBBFvvqxw** data, NimStringDesc* key, NI val);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_31)(void);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_32)(void);
N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_NIMCALL(void, sort_jFpBafF2fWVni1oyF0vlQQ_2)(CountTable_WWp0VSBtrctjwzspLeGpeg* t);
N_NIMCALL(NimStringDesc*, dollar__6eM2focZuoqC0uLzr9cX9cdQ)(CountTable_WWp0VSBtrctjwzspLeGpeg t);
N_NIMCALL(NI, len_c5UnrzkZ45eHDUGiXvcJ9aQ)(CountTable_WWp0VSBtrctjwzspLeGpeg t);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, amofDatInit000)(void);
NimStringDesc* doc_cb7bdoDQO9aiA39al9bmhg39aA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
Table_MCOwvEd9cS88yVcSkkw9bO9aQ args_TSWo6V660ucWPkA8JInOFQ;
extern TNimType NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_;
CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind_3JXiF5ExvnId6qlsFNQZCw;
NimStringDesc* key_HrPIgS3grYCz3bZmQe2JrA;
NimStringDesc* val_mPal8QwLfbhjE3pqo2GFVg;
extern TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
NimStringDesc* input_aAiBMUbHKAKFm8IoYadPvw;
Table_MCOwvEd9cS88yVcSkkw9bO9aQ seqs_AVhmyQIYAWY8iYJXltKidw;
NimStringDesc* id_OiciujkjgWykeTftLCNKyQ;
NI n_H9bAIGaagGdghcJa1YEGokA;
NimStringDesc* line_W3pnQg3Dut9c7VdSfhVccvg;
CountTable_WWp0VSBtrctjwzspLeGpeg fwords_fmELYjtI9awjMhFtz6n4rXA;
extern TNimType NTI_WWp0VSBtrctjwzspLeGpeg_;
NI motif_len_KsaQFfWNrquoGSrY2tVasQ;
NimStringDesc* motif_RR9bP9cLlXVm84eKhkazQ9b4w;
NimStringDesc* k_4GkAWpEwMKuSmPdbTbI16Q;
NimStringDesc* v_t9aUO7eGGnQWdBOCkRWp9abw;
NI n_H9bAIGaagGdghcJa1YEGokA_2;
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_3, "Welcome to aMOF basic documentation!\012\012Argument           Key   "
" Description\012\012config. file       -c     path/to/your/config.cfg\012"
"input file         -i     path/to/your/input.fasta\012output file  "
"      -o     path/to/your/output.txt\012algorithm          -a     r"
"un a particular algorithm\012method             -m     load a prede"
"fined method \012\012help               -h     print this help\012", 376);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_9, "h", 1);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_10, "running aMOF using the following params: ", 41);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_11, "input file:", 11);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_12, "i", 1);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_17, "\012", 1);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_21, ">", 1);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_22, "Error while parsing the input file at line ", 43);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_23, "::\'$#\'is not a valid FASTA::", 28);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_24, "::\'$#\' is not a valid FASTA::", 29);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_27, "Found ", 6);
STRING_LITERAL(TM_VcrzeMRV2mH4ebOSw10Paw_28, " sequences:", 11);
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_2)(void) {
	nimGCvisit((void*)doc_cb7bdoDQO9aiA39al9bmhg39aA, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_4)(void) {
	nimGCvisit((void*)args_TSWo6V660ucWPkA8JInOFQ.data, 0);
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(363, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_VcrzeMRV2mH4ebOSw10Paw_5;
	nimfr_("nextTry", "tableimpl.nim")
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_VcrzeMRV2mH4ebOSw10Paw_5 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_VcrzeMRV2mH4ebOSw10Paw_5) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_9b2gsSftUX2T20Nv0GQyaugtables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	nimfr_("rawGetDeep", "tableimpl.nim")
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_6)(void) {
	nimGCvisit((void*)key_HrPIgS3grYCz3bZmQe2JrA, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_7)(void) {
	nimGCvisit((void*)val_mPal8QwLfbhjE3pqo2GFVg, 0);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaug_2tables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_VcrzeMRV2mH4ebOSw10Paw_8;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = (t.data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = eqStrings(t.data->data[h].Field1, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_VcrzeMRV2mH4ebOSw10Paw_8 = subInt(((NI) -1), h);
	result = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_8);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_13)(void) {
	nimGCvisit((void*)input_aAiBMUbHKAKFm8IoYadPvw, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_14)(void) {
	nimGCvisit((void*)seqs_AVhmyQIYAWY8iYJXltKidw.data, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_15)(void) {
	nimGCvisit((void*)id_OiciujkjgWykeTftLCNKyQ, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_16)(void) {
	nimGCvisit((void*)line_W3pnQg3Dut9c7VdSfhVccvg, 0);
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim")
	result = (NimStringDesc*)0;
	nimln_(3345, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(290, "system.nim");
	result.a = a;
	nimln_(291, "system.nim");
	result.b = b;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_29)(void) {
	nimGCvisit((void*)fwords_fmELYjtI9awjMhFtz6n4rXA.data, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_30)(void) {
	nimGCvisit((void*)motif_RR9bP9cLlXVm84eKhkazQ9b4w, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_31)(void) {
	nimGCvisit((void*)k_4GkAWpEwMKuSmPdbTbI16Q, 0);
}
static N_NIMCALL(void, TM_VcrzeMRV2mH4ebOSw10Paw_32)(void) {
	nimGCvisit((void*)v_t9aUO7eGGnQWdBOCkRWp9abw, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_parseopt2DatInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	amofDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_parseopt2Init000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	NimStringDesc* T16_;
	NimStringDesc** T17_;
	NimStringDesc** T18_;
	NI T74_;
	NimStringDesc* T75_;
	NimStringDesc* T76_;
	NimStringDesc* T98_;
	nimfr_("amof", "amof.nim")
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_2);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_4);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_6);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_7);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_13);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_14);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_15);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_16);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_29);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_30);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_31);
nimRegisterGlobalMarker(TM_VcrzeMRV2mH4ebOSw10Paw_32);
	nimln_(4, "amof.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = doc_cb7bdoDQO9aiA39al9bmhg39aA; doc_cb7bdoDQO9aiA39al9bmhg39aA = copyStringRC1(((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_3));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(19, "amof.nim");
	chckNil((void*)(&args_TSWo6V660ucWPkA8JInOFQ));
	genericReset((void*)(&args_TSWo6V660ucWPkA8JInOFQ), (&NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_));
	initTable_Pb6nsyDUqkcuOfIqNGZ04Q(((NI) 64), (&args_TSWo6V660ucWPkA8JInOFQ));
	{
		OptParser_w3uFmxpwEmgEXFUJjUl10w p;
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		nimln_(146, "parseopt2.nim");
		chckNil((void*)(&p));
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		initOptParser_7ywjeToZhKr9cLpneviH7zg((&p));
		{
			nimln_(147, "parseopt2.nim");
			while (1) {
				NimStringDesc* T9_;
				NimStringDesc* T10_;
				nimln_(148, "parseopt2.nim");
				npo2next((&p));
				nimln_(149, "parseopt2.nim");
				{
					if (!(p.kind == ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0))) goto LA7_;
					goto LA3;
				}
				LA7_: ;
				nimln_(150, "parseopt2.nim");
				kind_3JXiF5ExvnId6qlsFNQZCw = p.kind;
				T9_ = (NimStringDesc*)0;
				T9_ = key_HrPIgS3grYCz3bZmQe2JrA; key_HrPIgS3grYCz3bZmQe2JrA = copyStringRC1(p.key);
				if (T9_) nimGCunrefNoCycle(T9_);
				T10_ = (NimStringDesc*)0;
				T10_ = val_mPal8QwLfbhjE3pqo2GFVg; val_mPal8QwLfbhjE3pqo2GFVg = copyStringRC1(p.val);
				if (T10_) nimGCunrefNoCycle(T10_);
				nimln_(25, "amof.nim");
				add_CM5QBhJw8HvPuuaSW9c6LyQ((&args_TSWo6V660ucWPkA8JInOFQ), key_HrPIgS3grYCz3bZmQe2JrA, val_mPal8QwLfbhjE3pqo2GFVg);
			}
		} LA3: ;
	}
	nimln_(27, "amof.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = hasKey_73Yi0wXG00JVMtJDwIey2w(args_TSWo6V660ucWPkA8JInOFQ, ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_9));
		if (!T13_) goto LA14_;
		nimln_(28, "amof.nim");
		printf("%s\012", doc_cb7bdoDQO9aiA39al9bmhg39aA? (doc_cb7bdoDQO9aiA39al9bmhg39aA)->data:"nil");
		fflush(stdout);
		nimln_(1426, "system.nim");
		exit(((NI) 0));
	}
	LA14_: ;
	nimln_(32, "amof.nim");
	T16_ = (NimStringDesc*)0;
	T16_ = dollar__cPfIGYedWWtjGdyyA7sVuw(args_TSWo6V660ucWPkA8JInOFQ);
	printf("%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_10)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_10))->data:"nil", T16_? (T16_)->data:"nil");
	fflush(stdout);
	nimln_(33, "amof.nim");
	T17_ = (NimStringDesc**)0;
	T17_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_TSWo6V660ucWPkA8JInOFQ), ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_12));
	printf("%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_11)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_11))->data:"nil", (*T17_)? ((*T17_))->data:"nil");
	fflush(stdout);
	nimln_(37, "amof.nim");
	T18_ = (NimStringDesc**)0;
	T18_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_TSWo6V660ucWPkA8JInOFQ), ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_12));
	asgnRefNoCycle((void**) (&input_aAiBMUbHKAKFm8IoYadPvw), readFile_T9cm5LIRX2tKEH9aREBZ8A0w((*T18_)));
	nimln_(38, "amof.nim");
	chckNil((void*)(&seqs_AVhmyQIYAWY8iYJXltKidw));
	genericReset((void*)(&seqs_AVhmyQIYAWY8iYJXltKidw), (&NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_));
	initTable_Pb6nsyDUqkcuOfIqNGZ04Q(((NI) 64), (&seqs_AVhmyQIYAWY8iYJXltKidw));
	nimln_(42, "amof.nim");
	n_H9bAIGaagGdghcJa1YEGokA = ((NI) 0);
	{
		NI last;
		NI splits;
		nimln_(504, "strutils.nim");
		last = ((NI) 0);
		nimln_(505, "strutils.nim");
		splits = ((NI) -1);
		nimln_(633, "strutils.nim");
		{
			nimln_(507, "strutils.nim");
			nimln_(633, "strutils.nim");
			if (!(((NI) 0) < (input_aAiBMUbHKAKFm8IoYadPvw ? input_aAiBMUbHKAKFm8IoYadPvw->Sup.len : 0))) goto LA22_;
			{
				nimln_(508, "strutils.nim");
				while (1) {
					NI first;
					NI TM_VcrzeMRV2mH4ebOSw10Paw_19;
					NI TM_VcrzeMRV2mH4ebOSw10Paw_20;
					NI TM_VcrzeMRV2mH4ebOSw10Paw_25;
					NI TM_VcrzeMRV2mH4ebOSw10Paw_26;
					nimln_(633, "strutils.nim");
					if (!(last <= (input_aAiBMUbHKAKFm8IoYadPvw ? input_aAiBMUbHKAKFm8IoYadPvw->Sup.len : 0))) goto LA25;
					nimln_(509, "strutils.nim");
					first = last;
					{
						nimln_(510, "strutils.nim");
						while (1) {
							NIM_BOOL T28_;
							NIM_BOOL T30_;
							NI TM_VcrzeMRV2mH4ebOSw10Paw_18;
							T28_ = (NIM_BOOL)0;
							nimln_(633, "strutils.nim");
							T28_ = (last < (input_aAiBMUbHKAKFm8IoYadPvw ? input_aAiBMUbHKAKFm8IoYadPvw->Sup.len : 0));
							if (!(T28_)) goto LA29_;
							nimln_(500, "strutils.nim");
							nimln_(633, "strutils.nim");
							T30_ = (NIM_BOOL)0;
							T30_ = substrEq_7ngl0F5lryTkSAj7sYQ7pw(input_aAiBMUbHKAKFm8IoYadPvw, last, ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_17));
							T28_ = !(T30_);
							LA29_: ;
							if (!T28_) goto LA27;
							nimln_(511, "strutils.nim");
							TM_VcrzeMRV2mH4ebOSw10Paw_18 = addInt(last, ((NI) 1));
							last = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_18);
						} LA27: ;
					}
					nimln_(512, "strutils.nim");
					{
						if (!(splits == ((NI) 0))) goto LA33_;
						nimln_(633, "strutils.nim");
						last = (input_aAiBMUbHKAKFm8IoYadPvw ? input_aAiBMUbHKAKFm8IoYadPvw->Sup.len : 0);
					}
					LA33_: ;
					nimln_(513, "strutils.nim");
					TM_VcrzeMRV2mH4ebOSw10Paw_19 = subInt(last, ((NI) 1));
					asgnRefNoCycle((void**) (&line_W3pnQg3Dut9c7VdSfhVccvg), copyStrLast(input_aAiBMUbHKAKFm8IoYadPvw, first, (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_19)));
					nimln_(44, "amof.nim");
					TM_VcrzeMRV2mH4ebOSw10Paw_20 = addInt(n_H9bAIGaagGdghcJa1YEGokA, ((NI) 1));
					n_H9bAIGaagGdghcJa1YEGokA = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_20);
					nimln_(45, "amof.nim");
					{
						nimln_(363, "system.nim");
						nimln_(45, "amof.nim");
						if (!!(((line_W3pnQg3Dut9c7VdSfhVccvg) && (line_W3pnQg3Dut9c7VdSfhVccvg)->Sup.len == 0))) goto LA37_;
						nimln_(46, "amof.nim");
						{
							NIM_BOOL T41_;
							T41_ = (NIM_BOOL)0;
							T41_ = contains_bKoQGynT9bWCEn79aXG8be9aw(line_W3pnQg3Dut9c7VdSfhVccvg, ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_21));
							if (!T41_) goto LA42_;
							nimln_(47, "amof.nim");
							{
								Slice_qL3WGViqT0p5sVr4YFHsLg T48_;
								if (!(id_OiciujkjgWykeTftLCNKyQ == NIM_NIL)) goto LA46_;
								nimln_(48, "amof.nim");
								T48_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 1), (line_W3pnQg3Dut9c7VdSfhVccvg ? (line_W3pnQg3Dut9c7VdSfhVccvg->Sup.len-1) : -1));
								asgnRefNoCycle((void**) (&id_OiciujkjgWykeTftLCNKyQ), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(line_W3pnQg3Dut9c7VdSfhVccvg, T48_));
							}
							goto LA44_;
							LA46_: ;
							{
								NimStringDesc* T50_;
								NimStringDesc** T51_;
								NimStringDesc* T52_;
								nimln_(50, "amof.nim");
								T50_ = (NimStringDesc*)0;
								T50_ = nimIntToStr(n_H9bAIGaagGdghcJa1YEGokA);
								printf("%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22))->data:"nil", T50_? (T50_)->data:"nil");
								fflush(stdout);
								nimln_(51, "amof.nim");
								T51_ = (NimStringDesc**)0;
								T51_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_TSWo6V660ucWPkA8JInOFQ), ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_12));
								T52_ = (NimStringDesc*)0;
								T52_ = nsuFormatSingleElem(((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_23), (*T51_));
								printf("%s\012", T52_? (T52_)->data:"nil");
								fflush(stdout);
								nimln_(1426, "system.nim");
								exit(((NI) 0));
							}
							LA44_: ;
						}
						goto LA39_;
						LA42_: ;
						{
							nimln_(54, "amof.nim");
							{
								NimStringDesc* T58_;
								nimln_(363, "system.nim");
								nimln_(54, "amof.nim");
								if (!!((id_OiciujkjgWykeTftLCNKyQ == NIM_NIL))) goto LA56_;
								nimln_(55, "amof.nim");
								add_CM5QBhJw8HvPuuaSW9c6LyQ((&seqs_AVhmyQIYAWY8iYJXltKidw), id_OiciujkjgWykeTftLCNKyQ, line_W3pnQg3Dut9c7VdSfhVccvg);
								nimln_(56, "amof.nim");
								T58_ = (NimStringDesc*)0;
								T58_ = id_OiciujkjgWykeTftLCNKyQ; id_OiciujkjgWykeTftLCNKyQ = copyStringRC1(NIM_NIL);
								if (T58_) nimGCunrefNoCycle(T58_);
							}
							goto LA54_;
							LA56_: ;
							{
								NimStringDesc* T60_;
								NimStringDesc** T61_;
								NimStringDesc* T62_;
								nimln_(58, "amof.nim");
								T60_ = (NimStringDesc*)0;
								T60_ = nimIntToStr(n_H9bAIGaagGdghcJa1YEGokA);
								printf("%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22))->data:"nil", T60_? (T60_)->data:"nil");
								fflush(stdout);
								nimln_(59, "amof.nim");
								T61_ = (NimStringDesc**)0;
								T61_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_TSWo6V660ucWPkA8JInOFQ), ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_12));
								T62_ = (NimStringDesc*)0;
								T62_ = nsuFormatSingleElem(((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_24), (*T61_));
								printf("%s\012", T62_? (T62_)->data:"nil");
								fflush(stdout);
								nimln_(1426, "system.nim");
								exit(((NI) 0));
							}
							LA54_: ;
						}
						LA39_: ;
					}
					LA37_: ;
					nimln_(514, "strutils.nim");
					{
						if (!(splits == ((NI) 0))) goto LA65_;
						goto LA24;
					}
					LA65_: ;
					nimln_(515, "strutils.nim");
					TM_VcrzeMRV2mH4ebOSw10Paw_25 = subInt(splits, ((NI) 1));
					splits = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_25);
					nimln_(516, "strutils.nim");
					TM_VcrzeMRV2mH4ebOSw10Paw_26 = addInt(last, ((NI) 1));
					last = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_26);
				} LA25: ;
			} LA24: ;
		}
		LA22_: ;
	}
	nimln_(61, "amof.nim");
	{
		NimStringDesc* T71_;
		NimStringDesc** T72_;
		NimStringDesc* T73_;
		nimln_(363, "system.nim");
		nimln_(61, "amof.nim");
		if (!!((id_OiciujkjgWykeTftLCNKyQ == NIM_NIL))) goto LA69_;
		nimln_(62, "amof.nim");
		T71_ = (NimStringDesc*)0;
		T71_ = nimIntToStr(n_H9bAIGaagGdghcJa1YEGokA);
		printf("%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_22))->data:"nil", T71_? (T71_)->data:"nil");
		fflush(stdout);
		nimln_(63, "amof.nim");
		T72_ = (NimStringDesc**)0;
		T72_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_TSWo6V660ucWPkA8JInOFQ), ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_12));
		T73_ = (NimStringDesc*)0;
		T73_ = nsuFormatSingleElem(((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_24), (*T72_));
		printf("%s\012", T73_? (T73_)->data:"nil");
		fflush(stdout);
		nimln_(1426, "system.nim");
		exit(((NI) 0));
	}
	LA69_: ;
	nimln_(68, "amof.nim");
	T74_ = (NI)0;
	T74_ = len_i2Zrth1XTX9c3vCk9aWi3N9bQ(seqs_AVhmyQIYAWY8iYJXltKidw);
	T75_ = (NimStringDesc*)0;
	T75_ = nimIntToStr(T74_);
	printf("%s%s%s\012", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_27)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_27))->data:"nil", T75_? (T75_)->data:"nil", ((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_28)? (((NimStringDesc*) &TM_VcrzeMRV2mH4ebOSw10Paw_28))->data:"nil");
	fflush(stdout);
	nimln_(69, "amof.nim");
	T76_ = (NimStringDesc*)0;
	T76_ = dollar__cPfIGYedWWtjGdyyA7sVuw(seqs_AVhmyQIYAWY8iYJXltKidw);
	printf("%s\012", T76_? (T76_)->data:"nil");
	fflush(stdout);
	nimln_(76, "amof.nim");
	chckNil((void*)(&fwords_fmELYjtI9awjMhFtz6n4rXA));
	genericReset((void*)(&fwords_fmELYjtI9awjMhFtz6n4rXA), (&NTI_WWp0VSBtrctjwzspLeGpeg_));
	initCountTable_n9cD2kEnW9cUab3V9bqtBxaTw(((NI) 64), (&fwords_fmELYjtI9awjMhFtz6n4rXA));
	nimln_(77, "amof.nim");
	motif_len_KsaQFfWNrquoGSrY2tVasQ = ((NI) 5);
	{
		{
			NI h;
			NI colontmp_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(244, "tables.nim");
			colontmp_ = (seqs_AVhmyQIYAWY8iYJXltKidw.data ? (seqs_AVhmyQIYAWY8iYJXltKidw.data->Sup.len-1) : -1);
			nimln_(1955, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1956, "system.nim");
				while (1) {
					NI TM_VcrzeMRV2mH4ebOSw10Paw_35;
					if (!(res <= colontmp_)) goto LA80;
					nimln_(1957, "system.nim");
					h = res;
					nimln_(245, "tables.nim");
					{
						NIM_BOOL T83_;
						NimStringDesc* T86_;
						NimStringDesc* T87_;
						if ((NU)(h) >= (NU)(seqs_AVhmyQIYAWY8iYJXltKidw.data->Sup.len)) raiseIndexError();
						T83_ = (NIM_BOOL)0;
						T83_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(seqs_AVhmyQIYAWY8iYJXltKidw.data->data[h].Field0);
						if (!T83_) goto LA84_;
						if ((NU)(h) >= (NU)(seqs_AVhmyQIYAWY8iYJXltKidw.data->Sup.len)) raiseIndexError();
						T86_ = (NimStringDesc*)0;
						T86_ = k_4GkAWpEwMKuSmPdbTbI16Q; k_4GkAWpEwMKuSmPdbTbI16Q = copyStringRC1(seqs_AVhmyQIYAWY8iYJXltKidw.data->data[h].Field1);
						if (T86_) nimGCunrefNoCycle(T86_);
						if ((NU)(h) >= (NU)(seqs_AVhmyQIYAWY8iYJXltKidw.data->Sup.len)) raiseIndexError();
						T87_ = (NimStringDesc*)0;
						T87_ = v_t9aUO7eGGnQWdBOCkRWp9abw; v_t9aUO7eGGnQWdBOCkRWp9abw = copyStringRC1(seqs_AVhmyQIYAWY8iYJXltKidw.data->data[h].Field2);
						if (T87_) nimGCunrefNoCycle(T87_);
						{
							NI colontmp__2;
							NI res_2;
							n_H9bAIGaagGdghcJa1YEGokA_2 = 0;
							colontmp__2 = (NI)0;
							nimln_(81, "amof.nim");
							colontmp__2 = (v_t9aUO7eGGnQWdBOCkRWp9abw ? v_t9aUO7eGGnQWdBOCkRWp9abw->Sup.len : 0);
							nimln_(1955, "system.nim");
							res_2 = ((NI) 0);
							{
								nimln_(1956, "system.nim");
								while (1) {
									NI TM_VcrzeMRV2mH4ebOSw10Paw_33;
									Slice_qL3WGViqT0p5sVr4YFHsLg T91_;
									NI TM_VcrzeMRV2mH4ebOSw10Paw_34;
									if (!(res_2 <= colontmp__2)) goto LA90;
									nimln_(1957, "system.nim");
									n_H9bAIGaagGdghcJa1YEGokA_2 = res_2;
									nimln_(82, "amof.nim");
									TM_VcrzeMRV2mH4ebOSw10Paw_33 = addInt(n_H9bAIGaagGdghcJa1YEGokA_2, motif_len_KsaQFfWNrquoGSrY2tVasQ);
									T91_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(n_H9bAIGaagGdghcJa1YEGokA_2, subInt((NI)(TM_VcrzeMRV2mH4ebOSw10Paw_33), 1));
									asgnRefNoCycle((void**) (&motif_RR9bP9cLlXVm84eKhkazQ9b4w), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(v_t9aUO7eGGnQWdBOCkRWp9abw, T91_));
									nimln_(83, "amof.nim");
									{
										nimln_(363, "system.nim");
										nimln_(83, "amof.nim");
										if (!!(((motif_RR9bP9cLlXVm84eKhkazQ9b4w ? motif_RR9bP9cLlXVm84eKhkazQ9b4w->Sup.len : 0) == motif_len_KsaQFfWNrquoGSrY2tVasQ))) goto LA94_;
										nimln_(84, "amof.nim");
										goto LA88;
									}
									goto LA92_;
									LA94_: ;
									{
										NimStringDesc* T97_;
										nimln_(86, "amof.nim");
										T97_ = (NimStringDesc*)0;
										T97_ = nsuToLowerAsciiStr(motif_RR9bP9cLlXVm84eKhkazQ9b4w);
										inc_hCwWEfjYY2mbkXPFg2lZFQ((&fwords_fmELYjtI9awjMhFtz6n4rXA), T97_, ((NI) 1));
									}
									LA92_: ;
									nimln_(1976, "system.nim");
									TM_VcrzeMRV2mH4ebOSw10Paw_34 = addInt(res_2, ((NI) 1));
									res_2 = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_34);
								} LA90: ;
							}
						} LA88: ;
					}
					LA84_: ;
					TM_VcrzeMRV2mH4ebOSw10Paw_35 = addInt(res, ((NI) 1));
					res = (NI)(TM_VcrzeMRV2mH4ebOSw10Paw_35);
				} LA80: ;
			}
		}
	}
	nimln_(88, "amof.nim");
	sort_jFpBafF2fWVni1oyF0vlQQ_2((&fwords_fmELYjtI9awjMhFtz6n4rXA));
	nimln_(89, "amof.nim");
	T98_ = (NimStringDesc*)0;
	T98_ = dollar__6eM2focZuoqC0uLzr9cX9cdQ(fwords_fmELYjtI9awjMhFtz6n4rXA);
	printf("%s\012", T98_? (T98_)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, amofDatInit000)(void) {
}

