/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/amarcozzi/homebrew/Cellar/nim/0.17.0/nim/lib -o /Users/amarcozzi/scripts/NIM_playground/nimcache/diceof.o /Users/amarcozzi/scripts/NIM_playground/nimcache/diceof.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Table_MCOwvEd9cS88yVcSkkw9bO9aQ Table_MCOwvEd9cS88yVcSkkw9bO9aQ;
typedef struct TY_SFipDZIkFtPcrLs0AGBBjQ TY_SFipDZIkFtPcrLs0AGBBjQ;
typedef struct TY_8ZxhPt1NwfElsJs8zUSV9bg TY_8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct OptParser_w3uFmxpwEmgEXFUJjUl10w OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct TNimObject TNimObject;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg;
typedef struct Slice_qL3WGViqT0p5sVr4YFHsLg Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct  Table_MCOwvEd9cS88yVcSkkw9bO9aQ  {
TY_SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct TY_8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NU8 CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct  TNimObject  {
TNimType* m_type;
};
struct  OptParser_w3uFmxpwEmgEXFUJjUl10w  {
  TNimObject Sup;
TY_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
void* ClE_0;
} TY_kTj9c3SX9agxDQPZYwemi6ug;
typedef NU8 SortOrder_8iBc6wlNqBa9cju9cUAhUAxA;
struct  Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg  {
NI colonstate_;
NimStringDesc* a1;
NimStringDesc* b2;
};
struct  Slice_qL3WGViqT0p5sVr4YFHsLg  {
NI a;
NI b;
};
typedef struct {
N_NIMCALL_PTR(TY_sM4lkSb7zS6F7OVMvW9cffQ*, ClP_0) (void* ClE_0);
void* ClE_0;
} TY_jGa0TDlm1RK7NwnvKCTNkQ;
typedef N_CLOSURE_PTR(TY_sM4lkSb7zS6F7OVMvW9cffQ*, TM_W0mC71nqkE32OHMh9ankdiQ_17) (void);
typedef N_CLOSURE_PTR(TY_sM4lkSb7zS6F7OVMvW9cffQ*, TM_W0mC71nqkE32OHMh9ankdiQ_21) (void);
typedef N_CLOSURE_PTR(NI, TM_W0mC71nqkE32OHMh9ankdiQ_22) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_W0mC71nqkE32OHMh9ankdiQ_23) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  TY_8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, initTable_Pb6nsyDUqkcuOfIqNGZ04Q)(NI initialSize, Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result);
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_4)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, add_CM5QBhJw8HvPuuaSW9c6LyQ)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, enlarge_9bBNTfkcWUAIzJYEZbqre3w)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t);
N_NIMCALL(void, rawInsert_i52hhunrCCXlXL7airLPUA)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, TY_SFipDZIkFtPcrLs0AGBBjQ** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_9b2gsSftUX2T20Nv0GQyaugtables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_6)(void);
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_7)(void);
N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NIMCALL(void, npo2next)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NIM_BOOL, hasKey_73Yi0wXG00JVMtJDwIey2w)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key);
static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaug_2tables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, sort_9a7klSx0Yu33UIahhT1Of7Q)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(void, merge_KHePwML9ba2tSMRLHxcf3EQ)(NimStringDesc** a, NI aLen_0, NimStringDesc** b, NI bLen_0, NI lo, NI m, NI hi, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(NF, dice_coefficient_kWHKMkrJrSqc3E31wLs8HQ)(NimStringDesc* a, NimStringDesc* b);
static N_NIMCALL(void, Marker_TY_i38o8cAJXByq9cKDfxzFmEg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ)(void* ClE_0);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ_2)(void* ClE_0);
N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_NIMCALL(NimStringDesc**, X5BX5D__IdJl6zz7UBsTsE2mzgQNJA)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, diceofDatInit000)(void);
NimStringDesc* doc_RjJsnv6iHumj2ToZzIpoqg;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
Table_MCOwvEd9cS88yVcSkkw9bO9aQ args_2otzTsrEd2pEyHbGbR5IcQ;
extern TNimType NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_;
CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind_TcVHSfbASwMfxgdbHUCAyw;
NimStringDesc* key_stbofb4YN7Y6zb9bpjBmbCA;
NimStringDesc* val_ReCya4qIBSPG9aIH25UOzdg;
extern TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
extern TNimType NTI_n0GV8cT30u289bzvb9bOzCmw_;
TNimType NTI_ZhEJP5xG9aadW74CvBiscOg_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
TNimType NTI_i38o8cAJXByq9cKDfxzFmEg_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_3, "Compute the Dice coefficient of two strings.\012\012Argument      Key"
"    Description\012\012string A      -a     First input string\012string "
"B      -b     Second input string\012\012help          -h     print th"
"is help\012", 199);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_8, "kind:", 5);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_9, "key :", 5);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_10, "val :", 5);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_12, "h", 1);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_30, "a", 1);
STRING_LITERAL(TM_W0mC71nqkE32OHMh9ankdiQ_31, "b", 1);
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_2)(void) {
	nimGCvisit((void*)doc_RjJsnv6iHumj2ToZzIpoqg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_4)(void) {
	nimGCvisit((void*)args_2otzTsrEd2pEyHbGbR5IcQ.data, 0);
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(363, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_W0mC71nqkE32OHMh9ankdiQ_5;
	nimfr_("nextTry", "tableimpl.nim")
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_W0mC71nqkE32OHMh9ankdiQ_5 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_W0mC71nqkE32OHMh9ankdiQ_5) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_9b2gsSftUX2T20Nv0GQyaugtables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	nimfr_("rawGetDeep", "tableimpl.nim")
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_6)(void) {
	nimGCvisit((void*)key_stbofb4YN7Y6zb9bpjBmbCA, 0);
}
static N_NIMCALL(void, TM_W0mC71nqkE32OHMh9ankdiQ_7)(void) {
	nimGCvisit((void*)val_ReCya4qIBSPG9aIH25UOzdg, 0);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaug_2tables)(Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_W0mC71nqkE32OHMh9ankdiQ_11;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = (t.data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = eqStrings(t.data->data[h].Field1, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_W0mC71nqkE32OHMh9ankdiQ_11 = subInt(((NI) -1), h);
	result = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_11);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_TY_i38o8cAJXByq9cKDfxzFmEg)(void* p, NI op) {
	Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg* a;
	a = (Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*)p;
	nimGCvisit((void*)(*a).a1, op);
	nimGCvisit((void*)(*a).b2, op);
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim")
	result = (NimStringDesc*)0;
	nimln_(3345, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(290, "system.nim");
	result.a = a;
	nimln_(291, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ)(void* ClE_0) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg* colonenvP_;
	nimfr_(":anonymous", "diceof.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	colonenvP_ = (Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*) ClE_0;
	nimln_(37, "diceof.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NI i;
		NI colontmp_;
		NI TM_W0mC71nqkE32OHMh9ankdiQ_14;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		TM_W0mC71nqkE32OHMh9ankdiQ_14 = subInt(((*colonenvP_).a1 ? (*colonenvP_).a1->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_14);
		nimln_(3772, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_W0mC71nqkE32OHMh9ankdiQ_15;
				Slice_qL3WGViqT0p5sVr4YFHsLg T4_;
				NimStringDesc* T5_;
				NimStringDesc* T6_;
				NI TM_W0mC71nqkE32OHMh9ankdiQ_16;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3774, "system.nim");
				i = i_2;
				nimln_(37, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_15 = addInt(i, ((NI) 2));
				T4_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(i, subInt((NI)(TM_W0mC71nqkE32OHMh9ankdiQ_15), 1));
				T5_ = (NimStringDesc*)0;
				T5_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem((*colonenvP_).a1, T4_);
				result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				T6_ = (NimStringDesc*)0;
				T6_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(T5_);
				if (T6_) nimGCunrefNoCycle(T6_);
				++result->Sup.len;
				nimln_(3775, "system.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_16 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_16);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ_2)(void* ClE_0) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg* colonenvP_;
	nimfr_(":anonymous", "diceof.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	colonenvP_ = (Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*) ClE_0;
	nimln_(38, "diceof.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NI i;
		NI colontmp_;
		NI TM_W0mC71nqkE32OHMh9ankdiQ_18;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		TM_W0mC71nqkE32OHMh9ankdiQ_18 = subInt(((*colonenvP_).b2 ? (*colonenvP_).b2->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_18);
		nimln_(3772, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_W0mC71nqkE32OHMh9ankdiQ_19;
				Slice_qL3WGViqT0p5sVr4YFHsLg T4_;
				NimStringDesc* T5_;
				NimStringDesc* T6_;
				NI TM_W0mC71nqkE32OHMh9ankdiQ_20;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3774, "system.nim");
				i = i_2;
				nimln_(38, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_19 = addInt(i, ((NI) 2));
				T4_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(i, subInt((NI)(TM_W0mC71nqkE32OHMh9ankdiQ_19), 1));
				T5_ = (NimStringDesc*)0;
				T5_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem((*colonenvP_).b2, T4_);
				result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				T6_ = (NimStringDesc*)0;
				T6_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(T5_);
				if (T6_) nimGCunrefNoCycle(T6_);
				++result->Sup.len;
				nimln_(3775, "system.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_20 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_20);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	int T13_;
{	result = (NI)0;
	{
		if (!(a == b)) goto LA3_;
		result = ((NI) 0);
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!(a == NIM_NIL)) goto LA7_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(b == NIM_NIL)) goto LA11_;
		result = ((NI) 1);
		goto BeforeRet_;
	}
	LA11_: ;
	T13_ = (int)0;
	T13_ = strcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)));
	result = ((NI) (T13_));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim")
	result = (NF)0;
	nimln_(3325, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, dice_coefficient_kWHKMkrJrSqc3E31wLs8HQ)(NimStringDesc* a, NimStringDesc* b) {
	NF result;
	Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg* colonenv_;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* a_bigram_list;
	TY_jGa0TDlm1RK7NwnvKCTNkQ T19_;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* b_bigram_list;
	TY_jGa0TDlm1RK7NwnvKCTNkQ T20_;
	NI lena;
	NI lenb;
	NI matches;
	NI i;
	NI j;
	TY_kTj9c3SX9agxDQPZYwemi6ug T21_;
	TY_kTj9c3SX9agxDQPZYwemi6ug T22_;
	NI TM_W0mC71nqkE32OHMh9ankdiQ_29;
	nimfr_("dice_coefficient", "diceof.nim")
{	result = (NF)0;
	colonenv_ = (Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*)0;
	nimln_(28, "diceof.nim");
	colonenv_ = (Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*) newObj((&NTI_i38o8cAJXByq9cKDfxzFmEg_), sizeof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg));
	T1_ = (NimStringDesc*)0;
	T1_ = (*colonenv_).a1; (*colonenv_).a1 = copyStringRC1(a);
	if (T1_) nimGCunrefNoCycle(T1_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*colonenv_).b2; (*colonenv_).b2 = copyStringRC1(b);
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(30, "diceof.nim");
	{
		NIM_BOOL T5_;
		T5_ = (NIM_BOOL)0;
		T5_ = (((*colonenv_).a1 ? (*colonenv_).a1->Sup.len : 0) == ((NI) 0));
		if (T5_) goto LA6_;
		T5_ = (((*colonenv_).b2 ? (*colonenv_).b2->Sup.len : 0) == ((NI) 0));
		LA6_: ;
		if (!T5_) goto LA7_;
		result = 0.0;
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(32, "diceof.nim");
	{
		if (!eqStrings((*colonenv_).a1, (*colonenv_).b2)) goto LA11_;
		result = 1.0000000000000000e+00;
		goto BeforeRet_;
	}
	LA11_: ;
	nimln_(34, "diceof.nim");
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = (((*colonenv_).a1 ? (*colonenv_).a1->Sup.len : 0) == ((NI) 1));
		if (T15_) goto LA16_;
		T15_ = (((*colonenv_).b2 ? (*colonenv_).b2->Sup.len : 0) == ((NI) 1));
		LA16_: ;
		if (!T15_) goto LA17_;
		result = 0.0;
		goto BeforeRet_;
	}
	LA17_: ;
	nimln_(37, "diceof.nim");
	memset((void*)(&T19_), 0, sizeof(T19_));
	T19_.ClP_0 = colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ; T19_.ClE_0 = colonenv_;
	a_bigram_list = T19_.ClE_0? T19_.ClP_0(T19_.ClE_0):((TM_W0mC71nqkE32OHMh9ankdiQ_17)(T19_.ClP_0))();
	nimln_(38, "diceof.nim");
	memset((void*)(&T20_), 0, sizeof(T20_));
	T20_.ClP_0 = colonanonymous__6fqN1cXjmpPzYrBLAGUmFQ_2; T20_.ClE_0 = colonenv_;
	b_bigram_list = T20_.ClE_0? T20_.ClP_0(T20_.ClE_0):((TM_W0mC71nqkE32OHMh9ankdiQ_21)(T20_.ClP_0))();
	nimln_(39, "diceof.nim");
	lena = (a_bigram_list ? a_bigram_list->Sup.len : 0);
	nimln_(40, "diceof.nim");
	lenb = (b_bigram_list ? b_bigram_list->Sup.len : 0);
	nimln_(41, "diceof.nim");
	matches = ((NI) 0);
	nimln_(42, "diceof.nim");
	i = ((NI) 0);
	nimln_(43, "diceof.nim");
	j = ((NI) 0);
	nimln_(45, "diceof.nim");
	memset((void*)(&T21_), 0, sizeof(T21_));
	T21_.ClP_0 = ((TM_W0mC71nqkE32OHMh9ankdiQ_22) (cmp_xEnKsp9cfvO7Do9cTYXo8eJw)); T21_.ClE_0 = NIM_NIL;
	sort_9a7klSx0Yu33UIahhT1Of7Q(a_bigram_list->data, a_bigram_list->Sup.len, T21_, ((SortOrder_8iBc6wlNqBa9cju9cUAhUAxA) 1));
	nimln_(46, "diceof.nim");
	memset((void*)(&T22_), 0, sizeof(T22_));
	T22_.ClP_0 = ((TM_W0mC71nqkE32OHMh9ankdiQ_23) (cmp_xEnKsp9cfvO7Do9cTYXo8eJw)); T22_.ClE_0 = NIM_NIL;
	sort_9a7klSx0Yu33UIahhT1Of7Q(b_bigram_list->data, b_bigram_list->Sup.len, T22_, ((SortOrder_8iBc6wlNqBa9cju9cUAhUAxA) 1));
	{
		nimln_(48, "diceof.nim");
		while (1) {
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = (i < lena);
			if (!(T25_)) goto LA26_;
			T25_ = (j < lenb);
			LA26_: ;
			if (!T25_) goto LA24;
			nimln_(49, "diceof.nim");
			{
				NI TM_W0mC71nqkE32OHMh9ankdiQ_24;
				NI TM_W0mC71nqkE32OHMh9ankdiQ_25;
				NI TM_W0mC71nqkE32OHMh9ankdiQ_26;
				if ((NU)(i) >= (NU)(a_bigram_list->Sup.len)) raiseIndexError();
				if ((NU)(j) >= (NU)(b_bigram_list->Sup.len)) raiseIndexError();
				if (!eqStrings(a_bigram_list->data[i], b_bigram_list->data[j])) goto LA29_;
				nimln_(50, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_24 = addInt(matches, ((NI) 2));
				matches = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_24);
				nimln_(51, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_25 = addInt(i, ((NI) 1));
				i = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_25);
				nimln_(52, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_26 = addInt(j, ((NI) 1));
				j = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_26);
			}
			goto LA27_;
			LA29_: ;
			{
				NI TM_W0mC71nqkE32OHMh9ankdiQ_27;
				nimln_(53, "diceof.nim");
				if ((NU)(i) >= (NU)(a_bigram_list->Sup.len)) raiseIndexError();
				if ((NU)(j) >= (NU)(b_bigram_list->Sup.len)) raiseIndexError();
				if (!(cmpStrings(a_bigram_list->data[i], b_bigram_list->data[j]) < 0)) goto LA32_;
				nimln_(54, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_27 = addInt(i, ((NI) 1));
				i = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_27);
			}
			goto LA27_;
			LA32_: ;
			{
				NI TM_W0mC71nqkE32OHMh9ankdiQ_28;
				nimln_(56, "diceof.nim");
				TM_W0mC71nqkE32OHMh9ankdiQ_28 = addInt(j, ((NI) 1));
				j = (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_28);
			}
			LA27_: ;
		} LA24: ;
	}
	nimln_(58, "diceof.nim");
	TM_W0mC71nqkE32OHMh9ankdiQ_29 = addInt(lena, lenb);
	result = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(matches, (NI)(TM_W0mC71nqkE32OHMh9ankdiQ_29));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_parseopt2DatInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	diceofDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_parseopt2Init000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	NimStringDesc** T16_;
	NimStringDesc** T17_;
	NF T18_;
	NimStringDesc* T19_;
	nimfr_("diceof", "diceof.nim")
nimRegisterGlobalMarker(TM_W0mC71nqkE32OHMh9ankdiQ_2);
nimRegisterGlobalMarker(TM_W0mC71nqkE32OHMh9ankdiQ_4);
nimRegisterGlobalMarker(TM_W0mC71nqkE32OHMh9ankdiQ_6);
nimRegisterGlobalMarker(TM_W0mC71nqkE32OHMh9ankdiQ_7);
	nimln_(4, "diceof.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = doc_RjJsnv6iHumj2ToZzIpoqg; doc_RjJsnv6iHumj2ToZzIpoqg = copyStringRC1(((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_3));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(16, "diceof.nim");
	chckNil((void*)(&args_2otzTsrEd2pEyHbGbR5IcQ));
	genericReset((void*)(&args_2otzTsrEd2pEyHbGbR5IcQ), (&NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_));
	initTable_Pb6nsyDUqkcuOfIqNGZ04Q(((NI) 64), (&args_2otzTsrEd2pEyHbGbR5IcQ));
	{
		OptParser_w3uFmxpwEmgEXFUJjUl10w p;
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		nimln_(146, "parseopt2.nim");
		chckNil((void*)(&p));
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		initOptParser_7ywjeToZhKr9cLpneviH7zg((&p));
		{
			nimln_(147, "parseopt2.nim");
			while (1) {
				NimStringDesc* T9_;
				NimStringDesc* T10_;
				nimln_(148, "parseopt2.nim");
				npo2next((&p));
				nimln_(149, "parseopt2.nim");
				{
					if (!(p.kind == ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0))) goto LA7_;
					goto LA3;
				}
				LA7_: ;
				nimln_(150, "parseopt2.nim");
				kind_TcVHSfbASwMfxgdbHUCAyw = p.kind;
				T9_ = (NimStringDesc*)0;
				T9_ = key_stbofb4YN7Y6zb9bpjBmbCA; key_stbofb4YN7Y6zb9bpjBmbCA = copyStringRC1(p.key);
				if (T9_) nimGCunrefNoCycle(T9_);
				T10_ = (NimStringDesc*)0;
				T10_ = val_ReCya4qIBSPG9aIH25UOzdg; val_ReCya4qIBSPG9aIH25UOzdg = copyStringRC1(p.val);
				if (T10_) nimGCunrefNoCycle(T10_);
				nimln_(19, "diceof.nim");
				printf("%s%s\012", ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_8)? (((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_8))->data:"nil", reprEnum((NI)kind_TcVHSfbASwMfxgdbHUCAyw, (&NTI_n0GV8cT30u289bzvb9bOzCmw_))? (reprEnum((NI)kind_TcVHSfbASwMfxgdbHUCAyw, (&NTI_n0GV8cT30u289bzvb9bOzCmw_)))->data:"nil");
				fflush(stdout);
				nimln_(20, "diceof.nim");
				printf("%s%s\012", ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_9)? (((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_9))->data:"nil", key_stbofb4YN7Y6zb9bpjBmbCA? (key_stbofb4YN7Y6zb9bpjBmbCA)->data:"nil");
				fflush(stdout);
				nimln_(21, "diceof.nim");
				printf("%s%s\012", ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_10)? (((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_10))->data:"nil", val_ReCya4qIBSPG9aIH25UOzdg? (val_ReCya4qIBSPG9aIH25UOzdg)->data:"nil");
				fflush(stdout);
				nimln_(22, "diceof.nim");
				add_CM5QBhJw8HvPuuaSW9c6LyQ((&args_2otzTsrEd2pEyHbGbR5IcQ), key_stbofb4YN7Y6zb9bpjBmbCA, val_ReCya4qIBSPG9aIH25UOzdg);
			}
		} LA3: ;
	}
	nimln_(24, "diceof.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = hasKey_73Yi0wXG00JVMtJDwIey2w(args_2otzTsrEd2pEyHbGbR5IcQ, ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_12));
		if (!T13_) goto LA14_;
		nimln_(25, "diceof.nim");
		printf("%s\012", doc_RjJsnv6iHumj2ToZzIpoqg? (doc_RjJsnv6iHumj2ToZzIpoqg)->data:"nil");
		fflush(stdout);
		nimln_(1426, "system.nim");
		exit(((NI) 0));
	}
	LA14_: ;
	nimln_(60, "diceof.nim");
	T16_ = (NimStringDesc**)0;
	T16_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_2otzTsrEd2pEyHbGbR5IcQ), ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_30));
	T17_ = (NimStringDesc**)0;
	T17_ = X5BX5D__IdJl6zz7UBsTsE2mzgQNJA((&args_2otzTsrEd2pEyHbGbR5IcQ), ((NimStringDesc*) &TM_W0mC71nqkE32OHMh9ankdiQ_31));
	T18_ = (NF)0;
	T18_ = dice_coefficient_kWHKMkrJrSqc3E31wLs8HQ((*T16_), (*T17_));
	T19_ = (NimStringDesc*)0;
	T19_ = nimFloatToStr(T18_);
	printf("%s\012", T19_? (T19_)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, diceofDatInit000)(void) {
static TNimNode* TM_W0mC71nqkE32OHMh9ankdiQ_13[3];
static TNimNode TM_W0mC71nqkE32OHMh9ankdiQ_0[4];
NTI_ZhEJP5xG9aadW74CvBiscOg_.size = sizeof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg);
NTI_ZhEJP5xG9aadW74CvBiscOg_.kind = 18;
NTI_ZhEJP5xG9aadW74CvBiscOg_.base = 0;
NTI_ZhEJP5xG9aadW74CvBiscOg_.flags = 2;
TM_W0mC71nqkE32OHMh9ankdiQ_13[0] = &TM_W0mC71nqkE32OHMh9ankdiQ_0[1];
TM_W0mC71nqkE32OHMh9ankdiQ_0[1].kind = 1;
TM_W0mC71nqkE32OHMh9ankdiQ_0[1].offset = offsetof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg, colonstate_);
TM_W0mC71nqkE32OHMh9ankdiQ_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_W0mC71nqkE32OHMh9ankdiQ_0[1].name = ":state";
TM_W0mC71nqkE32OHMh9ankdiQ_13[1] = &TM_W0mC71nqkE32OHMh9ankdiQ_0[2];
TM_W0mC71nqkE32OHMh9ankdiQ_0[2].kind = 1;
TM_W0mC71nqkE32OHMh9ankdiQ_0[2].offset = offsetof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg, a1);
TM_W0mC71nqkE32OHMh9ankdiQ_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_W0mC71nqkE32OHMh9ankdiQ_0[2].name = "a1";
TM_W0mC71nqkE32OHMh9ankdiQ_13[2] = &TM_W0mC71nqkE32OHMh9ankdiQ_0[3];
TM_W0mC71nqkE32OHMh9ankdiQ_0[3].kind = 1;
TM_W0mC71nqkE32OHMh9ankdiQ_0[3].offset = offsetof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg, b2);
TM_W0mC71nqkE32OHMh9ankdiQ_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_W0mC71nqkE32OHMh9ankdiQ_0[3].name = "b2";
TM_W0mC71nqkE32OHMh9ankdiQ_0[0].len = 3; TM_W0mC71nqkE32OHMh9ankdiQ_0[0].kind = 2; TM_W0mC71nqkE32OHMh9ankdiQ_0[0].sons = &TM_W0mC71nqkE32OHMh9ankdiQ_13[0];
NTI_ZhEJP5xG9aadW74CvBiscOg_.node = &TM_W0mC71nqkE32OHMh9ankdiQ_0[0];
NTI_i38o8cAJXByq9cKDfxzFmEg_.size = sizeof(Env_diceofdotnim__ZhEJP5xG9aadW74CvBiscOg*);
NTI_i38o8cAJXByq9cKDfxzFmEg_.kind = 22;
NTI_i38o8cAJXByq9cKDfxzFmEg_.base = (&NTI_ZhEJP5xG9aadW74CvBiscOg_);
NTI_i38o8cAJXByq9cKDfxzFmEg_.flags = 2;
NTI_i38o8cAJXByq9cKDfxzFmEg_.marker = Marker_TY_i38o8cAJXByq9cKDfxzFmEg;
}

