/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/amarcozzi/homebrew/Cellar/nim/0.17.0/nim/lib -o /Users/amarcozzi/scripts/NIM_playground/nimcache/stdlib_parseopt2.o /Users/amarcozzi/scripts/NIM_playground/nimcache/stdlib_parseopt2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct OptParser_w3uFmxpwEmgEXFUJjUl10w OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Slice_qL3WGViqT0p5sVr4YFHsLg Slice_qL3WGViqT0p5sVr4YFHsLg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef NU8 CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct  OptParser_w3uFmxpwEmgEXFUJjUl10w  {
  TNimObject Sup;
TY_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY_nmiMWKVIe46vacnhAFrQvw_Set[32];
typedef NIM_CHAR TY_1N75LKnZklmK4NsXtZ9bZiA[2];
struct  Slice_qL3WGViqT0p5sVr4YFHsLg  {
NI a;
NI b;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, eqeq__SRlIwYUUH1G46Yee9aMIFAQ)(TY_sM4lkSb7zS6F7OVMvW9cffQ* x, TY_sM4lkSb7zS6F7OVMvW9cffQ* y);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, at__s2ocO7QwvJg5hna9a9a004sw)(NimStringDesc** a, NI aLen_0);
N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, initOptParser_l6uHwLXJlTbbc0Q3R9agjwg)(NimStringDesc* cmdline, OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitCharSet)(NimStringDesc* s, TY_nmiMWKVIe46vacnhAFrQvw_Set seps, NI maxsplit);
N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty);
N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, npo2next)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__CV9a2fojnWgtmE9c1IX0QsKQ)(TY_sM4lkSb7zS6F7OVMvW9cffQ* s, Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, npo2cmdLineRest)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_n0GV8cT30u289bzvb9bOzCmw_;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_2, "", 0);
static NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set TM_hJtUwp9bs9cZbgrKsWuACD3Q_7 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
NIM_CONST TY_1N75LKnZklmK4NsXtZ9bZiA TM_hJtUwp9bs9cZbgrKsWuACD3Q_8 = {58,
61}
;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_16, "--", 2);
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_18, "-", 1);
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_21, " ", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	nimfr_("initOptParser", "parseopt2.nim")
{	nimln_(49, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).remainingShortOptions), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2)));
	nimln_(51, "parseopt2.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__SRlIwYUUH1G46Yee9aMIFAQ(cmdline, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(52, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
		nimln_(53, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(57, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).cmd), at__s2ocO7QwvJg5hna9a9a004sw(cmdline->data, cmdline->Sup.len));
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, initOptParser_l6uHwLXJlTbbc0Q3R9agjwg)(NimStringDesc* cmdline, OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	nimfr_("initOptParser", "parseopt2.nim")
{	nimln_(63, "parseopt2.nim");
	{
		if (!((cmdline) && (cmdline)->Sup.len == 0)) goto LA3_;
		nimln_(64, "parseopt2.nim");
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
		(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		initOptParser_sdCSBPv59coXTEz3qwUXMeA(NIM_NIL, Result);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		TY_sM4lkSb7zS6F7OVMvW9cffQ* T6_;
		nimln_(66, "parseopt2.nim");
		T6_ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		T6_ = nsuSplitCharSet(cmdline, TM_hJtUwp9bs9cZbgrKsWuACD3Q_7, ((NI) -1));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
		(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		initOptParser_sdCSBPv59coXTEz3qwUXMeA(T6_, Result);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* T1_;
	nimfr_("initOptParser", "parseopt2.nim")
{	nimln_(71, "parseopt2.nim");
	T1_ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ();
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	initOptParser_sdCSBPv59coXTEz3qwUXMeA(T1_, Result);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim")
	result = (NimStringDesc*)0;
	nimln_(3345, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(290, "system.nim");
	result.a = a;
	nimln_(291, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty) {
	nimfr_("nextOption", "parseopt2.nim")
{	{
		NIM_CHAR splitchar;
		NI i;
		splitchar = (NIM_CHAR)0;
		nimln_(2066, "system.nim");
		i = ((NI) 0);
		nimln_(2067, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				nimln_(2068, "system.nim");
				while (1) {
					NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_12;
					nimln_(2069, "system.nim");
					splitchar = TM_hJtUwp9bs9cZbgrKsWuACD3Q_8[(i)- 0];
					nimln_(77, "parseopt2.nim");
					{
						NIM_BOOL T10_;
						NI pos;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_9;
						Slice_qL3WGViqT0p5sVr4YFHsLg T13_;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_10;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_11;
						Slice_qL3WGViqT0p5sVr4YFHsLg T14_;
						T10_ = (NIM_BOOL)0;
						T10_ = contains_6e5MGL10HDAJ205lBYpWxw(token, splitchar);
						if (!T10_) goto LA11_;
						nimln_(78, "parseopt2.nim");
						pos = nsuFindChar(token, splitchar, ((NI) 0), ((NI) 0));
						nimln_(79, "parseopt2.nim");
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_9 = subInt(pos, ((NI) 1));
						T13_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_9));
						unsureAsgnRef((void**) (&(*p).key), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(token, T13_));
						nimln_(80, "parseopt2.nim");
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_10 = addInt(pos, ((NI) 1));
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_11 = subInt((token ? token->Sup.len : 0), ((NI) 1));
						T14_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes((NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_10), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_11));
						unsureAsgnRef((void**) (&(*p).val), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(token, T14_));
						nimln_(81, "parseopt2.nim");
						goto BeforeRet_;
					}
					LA11_: ;
					nimln_(2070, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA17_;
						goto LA6;
					}
					LA17_: ;
					nimln_(2071, "system.nim");
					TM_hJtUwp9bs9cZbgrKsWuACD3Q_12 = addInt(i, ((NI) 1));
					if (TM_hJtUwp9bs9cZbgrKsWuACD3Q_12 < 0 || TM_hJtUwp9bs9cZbgrKsWuACD3Q_12 > 1) raiseOverflow();
					i = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_12);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(83, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*p).key), copyString(token));
	nimln_(84, "parseopt2.nim");
	{
		if (!allowEmpty) goto LA21_;
		nimln_(85, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2)));
	}
	goto LA19_;
	LA21_: ;
	{
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_13;
		Slice_qL3WGViqT0p5sVr4YFHsLg T24_;
		nimln_(87, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_13 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T24_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_13));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(token, T24_));
		nimln_(88, "parseopt2.nim");
		npo2next(p);
	}
	LA19_: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, npo2next)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p) {
	NimStringDesc* token;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_15;
	nimfr_("next", "parseopt2.nim")
{	nimln_(91, "parseopt2.nim");
	{
		Slice_qL3WGViqT0p5sVr4YFHsLg T5_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_14;
		Slice_qL3WGViqT0p5sVr4YFHsLg T6_;
		nimln_(363, "system.nim");
		nimln_(91, "parseopt2.nim");
		if (!!((((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0) == ((NI) 0)))) goto LA3_;
		nimln_(92, "parseopt2.nim");
		(*p).kind = ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		nimln_(93, "parseopt2.nim");
		T5_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), ((NI) 0));
		unsureAsgnRef((void**) (&(*p).key), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem((*p).remainingShortOptions, T5_));
		nimln_(94, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2)));
		nimln_(95, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_14 = subInt(((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0), ((NI) 1));
		T6_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 1), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_14));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem((*p).remainingShortOptions, T6_));
		nimln_(96, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(98, "parseopt2.nim");
	{
		if (!(((*p).cmd ? (*p).cmd->Sup.len : 0) <= (*p).pos)) goto LA9_;
		nimln_(99, "parseopt2.nim");
		(*p).kind = ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0);
		nimln_(100, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(102, "parseopt2.nim");
	if ((NU)((*p).pos) >= (NU)((*p).cmd->Sup.len)) raiseIndexError();
	token = (*p).cmd->data[(*p).pos];
	nimln_(103, "parseopt2.nim");
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_15 = addInt((*p).pos, ((NI) 1));
	(*p).pos = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_15);
	nimln_(105, "parseopt2.nim");
	{
		NIM_BOOL T13_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_17;
		Slice_qL3WGViqT0p5sVr4YFHsLg T16_;
		NimStringDesc* T17_;
		T13_ = (NIM_BOOL)0;
		T13_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_16));
		if (!T13_) goto LA14_;
		nimln_(106, "parseopt2.nim");
		(*p).kind = ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 2);
		nimln_(107, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_17 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T16_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 2), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_17));
		T17_ = (NimStringDesc*)0;
		T17_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(token, T16_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T17_, NIM_TRUE);
	}
	goto LA11_;
	LA14_: ;
	{
		NIM_BOOL T19_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_19;
		Slice_qL3WGViqT0p5sVr4YFHsLg T22_;
		NimStringDesc* T23_;
		nimln_(108, "parseopt2.nim");
		T19_ = (NIM_BOOL)0;
		T19_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_18));
		if (!T19_) goto LA20_;
		nimln_(109, "parseopt2.nim");
		(*p).kind = ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		nimln_(110, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_19 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T22_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 1), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_19));
		T23_ = (NimStringDesc*)0;
		T23_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(token, T22_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T23_, NIM_TRUE);
	}
	goto LA11_;
	LA20_: ;
	{
		nimln_(112, "parseopt2.nim");
		(*p).kind = ((CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 1);
		nimln_(113, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).key), copyString(token));
		nimln_(114, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2)));
	}
	LA11_: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, npo2cmdLineRest)(OptParser_w3uFmxpwEmgEXFUJjUl10w* p) {
	NimStringDesc* result;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_20;
	Slice_qL3WGViqT0p5sVr4YFHsLg T1_;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* T2_;
	nimfr_("cmdLineRest", "parseopt2.nim")
{	result = (NimStringDesc*)0;
	nimln_(119, "parseopt2.nim");
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_20 = subInt(((*p).cmd ? (*p).cmd->Sup.len : 0), ((NI) 1));
	T1_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes((*p).pos, (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_20));
	T2_ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T2_ = X5BX5D__CV9a2fojnWgtmE9c1IX0QsKQ((*p).cmd, T1_);
	result = nsuJoinSep(T2_->data, T2_->Sup.len, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_21));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void) {
	nimfr_("parseopt2", "parseopt2.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void) {
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[6];
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[4];
NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_6;
static char* NIM_CONST TM_hJtUwp9bs9cZbgrKsWuACD3Q_5[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[12];
NTI_w3uFmxpwEmgEXFUJjUl10w_.size = sizeof(OptParser_w3uFmxpwEmgEXFUJjUl10w);
NTI_w3uFmxpwEmgEXFUJjUl10w_.kind = 17;
NTI_w3uFmxpwEmgEXFUJjUl10w_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[0] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, cmd);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].name = "cmd";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[1] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, pos);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].name = "pos";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[2] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, remainingShortOptions);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].name = "remainingShortOptions";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[3] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4];
NTI_n0GV8cT30u289bzvb9bOzCmw_.size = sizeof(CmdLineKind_n0GV8cT30u289bzvb9bOzCmw);
NTI_n0GV8cT30u289bzvb9bOzCmw_.kind = 14;
NTI_n0GV8cT30u289bzvb9bOzCmw_.base = 0;
NTI_n0GV8cT30u289bzvb9bOzCmw_.flags = 3;
for (TM_hJtUwp9bs9cZbgrKsWuACD3Q_6 = 0; TM_hJtUwp9bs9cZbgrKsWuACD3Q_6 < 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_6++) {
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6+5].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6+5].offset = TM_hJtUwp9bs9cZbgrKsWuACD3Q_6;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6+5].name = TM_hJtUwp9bs9cZbgrKsWuACD3Q_5[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_6+5];
}
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].len = 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[0];
NTI_n0GV8cT30u289bzvb9bOzCmw_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, kind);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].typ = (&NTI_n0GV8cT30u289bzvb9bOzCmw_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].name = "kind";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[4] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, key);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].name = "key";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[5] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].offset = offsetof(OptParser_w3uFmxpwEmgEXFUJjUl10w, val);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].name = "val";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].len = 6; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[0];
NTI_w3uFmxpwEmgEXFUJjUl10w_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0];
}

